version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: C0NTR4S3N4
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:C0NTR4S3N4@db:5432/taskmanager
      JWT_SECRET: mi_clave_secreta
      PORT: 3000
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./task-manager
      args:
        VITE_API_URL: http://localhost:3000
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data: